namespace Klyte.Commons.UI.Sprites
{
    public enum LineIconSpriteNames
    {
        NULL,
        K45_MapIcon,
        K45_OvalIcon,
        K45_RoundedHexagonIcon,
        K45_RoundedPentagonIcon,
        K45_RoundedTriangleIcon,
        K45_OctagonIcon,
        K45_HeptagonIcon,
        K45_S10StarIcon,
        K45_S09StarIcon,
        K45_S07StarIcon,
        K45_S06StarIcon,
        K45_S05StarIcon,
        K45_S04StarIcon,
        K45_S03StarIcon,
        K45_CameraIcon,
        K45_MountainIcon,
        K45_ConeIcon,
        K45_TriangleIcon,
        K45_CrossIcon,
        K45_DepotIcon,
        K45_ParachuteIcon,
        K45_HexagonIcon,
        K45_SquareIcon,
        K45_PentagonIcon,
        K45_TrapezeIcon,
        K45_DiamondIcon,
        K45_S08StarIcon,
        K45_CircleIcon,
        K45_RoundedSquareIcon
    };
}
